version: '3.3'

services: 
  squidproxy:
    image: dbgso/squid-proxy-blacklist
    container_name: squidproxy
    ports: 
      - 3128:3128
    restart: always
    volumes: 
      - ./config:/etc/squid
      - ./logs:/var/log/squid
      - ./cache:/var/cache/squid
    tty: true
      